web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_admin_password

ota:
  password: !secret esphome_admin_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name} - FB
    password: !secret esphome_admin_password

captive_portal:

logger:

api:
  encryption:
    key: !secret esphome_api_key
  id: espapi
  reboot_timeout: 5min
