packages:
  nexxtender: 
    url: https://github.com/geertmeersman/nexxtender
    file: config/nexxtender.yaml
    refresh: 1d
  
substitutions:
  device_name: nexxtender
  friendly_name: Nexxtender
  update_interval: 60s
