packages:
  esp: github://geertmeersman/nexxtender/config/nexxtender_packages/esp.yaml
  #webserver: github://geertmeersman/nexxtender/config/nexxtender_packages/webserver.yaml # secret esphome_admin_password required
  api: github://geertmeersman/nexxtender/config/nexxtender_packages/api.yaml # secrets esphome_admin_password, wifi_ssid, wifi_password & esphome_api_key required
  time: github://geertmeersman/nexxtender/config/nexxtender_packages/time.yaml
  ble: github://geertmeersman/nexxtender/config/nexxtender_packages/ble.yaml # secrets nexxtender_mac & nexxtender_passkey required
  device_information: github://geertmeersman/nexxtender/config/nexxtender_packages/device_information.yaml
  generic_data: github://geertmeersman/nexxtender/config/nexxtender_packages/generic_data.yaml
  charging_car_data: github://geertmeersman/nexxtender/config/nexxtender_packages/charging_car_data.yaml
  charging_grid_data: github://geertmeersman/nexxtender/config/nexxtender_packages/charging_grid_data.yaml
  charging_basic_data: github://geertmeersman/nexxtender/config/nexxtender_packages/charging_basic_data.yaml
  charging_advanced_data: github://geertmeersman/nexxtender/config/nexxtender_packages/charging_advanced_data.yaml
  #transactions: github://geertmeersman/nexxtender/config/nexxtender_packages/transactions.yaml
  #diagnostics: github://geertmeersman/nexxtender/config/nexxtender_packages/diagnostics.yaml
  
substitutions:
  device_name: nexxtender
  friendly_name: Nexxtender
  update_interval: 60s
