globals:
  - id: g_wifi_connected
    type: bool
    initial_value: "false"

ota:
  - platform: esphome
    password: !secret esphome_admin_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name} - FB
    password: !secret esphome_admin_password
  on_connect:
    then:
      - lambda: |-
          id(g_wifi_connected) = true;
  on_disconnect:
    then:
      - lambda: |-
          id(g_wifi_connected) = false;

captive_portal:

logger:

api:
  encryption:
    key: !secret esphome_api_key
  id: espapi
  reboot_timeout: 5min
