substitutions:
  device_name: nexxtender
  friendly_name: Nexxtender

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  includes:
    - nexxtender_packages/nexxtender.h
