packages:
  esp: !include packages/esp.yaml
  #webserver: !include packages/webserver.yaml # secret esphome_admin_password required
  api: !include packages/api.yaml # secrets esphome_admin_password, wifi_ssid, wifi_password & esphome_api_key required
  time: !include packages/time.yaml
  ble: !include packages/ble.yaml # secrets nexxtender_mac & nexxtender_passkey required
  generic_data: !include packages/generic_data.yaml
  charging_grid_data: !include packages/charging_grid_data.yaml
  charging_basic_data: !include packages/charging_basic_data.yaml
  #diagnostics: !include packages/diagnostics.yaml
  
substitutions:
  device_name: nexxtender
  friendly_name: Nexxtender
  update_interval: 60s
