name: ESPHome Build

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Move Secrets Template
        run: |
          cp config/secrets.yaml.template config/secrets.yaml
          sed -i 's/YOUR_ESPHOME_API_KEY/2EhugO+jJDJ+BiVEiRxzXnkDWTmxpdfvgdMXRv26\/pA=/' config/secrets.yaml
          sed -i 's/YOUR_NEXXTENDER_MAC_ADDRESS/00:1A:7D:DA:71:13/' config/secrets.yaml
          sed -i 's/YOUR_NEXXTENDER_PASSKEY/123456/' config/secrets.yaml
          echo "Secrets template moved."
        working-directory: ${{ github.workspace }}

      - name: Build ESPHOME
        uses: esphome/build-action@v1
        with:
          yaml_file: config/nexxtender.yaml
